# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-21 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
