# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-21 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import scanner.models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20160421_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='token',
            field=models.CharField(default=scanner.models.generate_random_password, max_length=256),
        ),
    ]
