# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-23 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_auto_20160423_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblog',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
    ]
