# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-05 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_joblog_parsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='scanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='scanner.Scanner'),
        ),
        migrations.AlterField(
            model_name='joblog',
            name='scanner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='scanner.Scanner'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanners', to='scanner.Scan'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='joblog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_results', to='scanner.JobLog'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_results', to='scanner.Scan'),
        ),
    ]
