# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-13 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_auto_20160505_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='external_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
